name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    env:
      PYTHON: ""
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1']
        julia-arch: [x64, x86]
        os: [ubuntu-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Format code
        if: ${{ matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request' }}
        run: |
          using Pkg
          Pkg.add(; name="JuliaFormatter", uuid="98e50ef6-434e-11e9-1051-2b60c6c9e899")
          using JuliaFormatter
          format("."; verbose=true)
        shell: julia --color=yes {0}
      - uses: reviewdog/action-suggester@v1
        if: ${{ matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request' }}
        with:
          tool_name: JuliaFormatter
          fail_on_error: true
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ matrix.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ matrix.os }}-test-${{ env.cache-name }}-
            ${{ matrix.os }}-test-
            ${{ matrix.os }}-
      - name: Build Package
        uses: julia-actions/julia-buildpkg@v1
      - name: Run Tests
        uses: julia-actions/julia-runtest@v1
      - name: Process Coverage
        uses: julia-actions/julia-processcoverage@v1
      - name: Codecov Coverage
        uses: codecov/codecov-action@v1
        with:
          file: lcov.info
